<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Parsley</string>
    <key>scopeName</key>
    <string>source.parsley</string>
    <key>fileTypes</key>
    <array>
      <string>.parsley</string>
    </array>
    <key>repository</key>
    <dict>
      <key>singleVariable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.complex</string>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>comment.block</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>comment.block</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#allStrings</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>statementKeywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.parsley</string>
            <key>match</key>
            <string>(^)?( )?(if|each|end-each|end-if|(else( |-)if))(( )|($))?</string>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.complex</string>
            <key>begin</key>
            <string>(\{\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>comment.block</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\}\})</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>comment.block</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#singleVariable</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#statementKeywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#eachOperators</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>blockComments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.annotation.parsley</string>
            <key>begin</key>
            <string>\(\*\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.annotation</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*\*\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.annotation</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#allStrings</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>allStrings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>.</string>
          </dict>
        </array>
      </dict>
      <key>eachOperators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.parsley</string>
            <key>match</key>
            <string>=</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#blockComments</string>
      </dict>
    </array>
  </dict>
</plist>